<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?pydev-testrun version="1.0"?><pydev-testsuite>
    <summary errors="1" failures="0" finished="true" name="Test Run: 1" tests="0" total_time="Finished in: 0.00 secs."/>
    <test location="C:/Users/jdunh/Documents/UD Extra Curriculars/Mars Rover/Robot Code/Video Test/Video_Test.py" status="error" test="Video_Test" time="0">
        <stdout/>
        <stderr><![CDATA[Traceback (most recent call last):
  File "C:\Users\jdunh\.p2\pool\plugins\org.python.pydev.core_9.1.0.202110031145\pysrc\_pydev_runfiles\pydev_runfiles.py", line 468, in __get_module_from_str
    mod = __import__(modname)
  File "C:\Users\jdunh\Documents\UD Extra Curriculars\Mars Rover\Robot Code\Video Test\Video_Test.py", line 7, in <module>
    face_cascade.load(cv2.samples.findFile("static/haarcascade_frontalface_alt.xml"))
cv2.error: OpenCV(4.6.0) D:\a\opencv-python\opencv-python\opencv\modules\core\src\utils\samples.cpp:64: error: (-2:Unspecified error) OpenCV samples: Can't find required data file: static/haarcascade_frontalface_alt.xml in function 'cv::samples::findFile'

ERROR: Module: Video_Test could not be imported (file: C:/Users/jdunh/Documents/UD Extra Curriculars/Mars Rover/Robot Code/Video Test/Video_Test.py).
]]></stderr>
    </test>
    <launch mode="run">
        <launch_memento><![CDATA[<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<launchConfiguration local="true" path="Video Test Video Test"/>
]]></launch_memento>
    </launch>
</pydev-testsuite>
